### ISSUE TITLE
Bug in xxHash

### ISSUE THREAD

**Issue by leventov** [chdir/fdutil#1]
https://github.com/chdir/fdutil/blob/ccde8da381ffc8e3df0710063a464aa365158c96/fdlib/src/main/java/net/openhft/hashing/XxHash_r39_Custom.java#L223

See https://github.com/OpenHFT/Zero-Allocation-Hashing/commit/8a6d6a1162f8a704eb3ffc2648fdae7a39885fcd

**Comment by Alexander--** [comment]
@leventov Do you know if this actually affect anything (besides symmetry with native xxHash implementation)?

**Comment by leventov** [comment]
@Alexander-- it affects the consistency of the `LongHashFunctionImplementation` -- e. g. it returns different results for `hashInt(v)` and `hashInts(new int[] {v})` and `hashBytes(nativeByteBuffer().putInt(0, v), 0, 4))`

I don't know, if this is important for your application or not.

**Comment by Alexander--** [comment]
@leventov Seems like there wasn't any impact on correctness in my case (I was using the library to hash char sequences only). Nevertheless, thanks for your effort!

**Comment by Alexander--** [comment]
New version with updated dependency has been released, closing.
